const products = [
    {
        productName: "OXFORD SHIRT TOMMY HILFIGER",
        category: ["Shirts"],
        price: "30",
        image: "oxford.webp",
        size: ["S", "M", "XXL"],
        sale: true,
    },
    {
        productName: "GANT GINGHAM SHIRT",
        category: ["Shirts"],
        price: "49",
        image: "gant.webp",
        size: ["L"],
        sale: false,
    },
    {
        productName: "LUMBERJACK SHIRT",
        category: ["Shirts"],
        price: "49",
        image: "lumberjackshirt.webp",
        size: ["S"],
        sale: false,
    },
    {
        productName: "BOSS SLIM FIT JEANS",
        category: ["Jeans"],
        price: "99",
        image: "boss.webp",
        size: ["44", "52"],
        sale: false,
    },
    {
        productName: "ARMANI POCKETS PANT",
        category: ["Jeans"],
        price: "129",
        image: "armani.webp",
        size: ["48", "50", "52"],
        sale: false,
    },
    {
        productName: "RALPH LAUREN AERA LACE",
        category: ["Shoes"],
        price: "129",
        image: "polo.webp",
        size: ["38", "39", "43", "44"],
        sale: true,
    },
    {
        productName: "RALPH LAUREN HERITAGE",
        category: ["Shoes"],
        price: "110",
        image: "polo2.webp",
        size: ["44"],
        sale: false,
    },
    {
        productName: "CLOSURE JACKET LONDON",
        category: ["Jackets"],
        price: "189",
        image: "london.webp",
        size: ["L", "XL"],
        sale: false,
    },
    {
        productName: "JACK JONES LONG PUFFER",
        category: ["Jackets"],
        price: "77",
        image: "jack.webp",
        size: ["S", "M", "L", "XL"],
        sale: false,
    },
    {
        productName: "POLO RALPH LAUREN ROUND",
        category: ["Sunglasses", "Accessories"],
        price: "111",
        image: "sunRalph.webp",
        size: [""],
        sale: true,
    },
    {
        productName: "OMNITRIX",
        category: ["Watches", "Accessories"],
        price: "???",
        image: "omnitrix.webp",
        size: [""],
        sale: true,
    },
];

// export default products;
